name: "task-manager"

services:
  proxy01:
    build:
      context: "."
      dockerfile: "proxy01/Dockerfile"
    networks:
      - internet
      - proxy
    ports:
      - "9000:8080"

  frontend:
    build:
      context: "."
      dockerfile: "frontend/Dockerfile"
      args:
        DKR_UID: 1000
        DKR_GID: 1000
    volumes:
      - "./frontend:/frontend:rw"
      - "./frontend/docker_node_modules:/frontend/node_modules:rw"
    user: "1000:1000"
    networks:
      - internet
      - proxy
    ports:
      - "9001:8080"

  backend:
    build: "backend"
    environment:
      MONGODB_CONNECTION_URI: "mongodb://task-manager-admin:replace-this-password@database-service:27017/"
    # secrets:
    #   - backend_mongodb_connection_uri
    networks:
      internet: {}
      proxy:
        aliases:
          - backend-proxy
      service: {}

  notifier-service:
    build: "notifier-service"
    networks:
      internet: {}
      proxy:
        aliases:
          - notifier-service-proxy

  database:
    image: mongo:8.0-noble
    environment:
      MONGO_INITDB_DATABASE: "task-manager"
      MONGO_INITDB_ROOT_USERNAME: "task-manager-admin"
      MONGO_INITDB_ROOT_PASSWORD: "replace-this-password"
    volumes:
      - db-data:/data/db
      - db-config:/data/configdb
    ports:
      - "27018:27017"
    networks:
      internet: {}
      service:
        aliases:
          - database-service

volumes:
  db-data: {}
  db-config: {}

# secrets:
#   backend_mongodb_connection_uri:
#     file: "../secrets/backend/mongodb_connection_uri"

networks:
  internet:
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"
  proxy:
    internal: true
  service:
    internal: true
