name: "task-manager-dev"

services:
  proxy01:
    extends:
      file: "../compose.yaml"
      service: proxy01

  frontend:
    extends:
      file: "../compose.yaml"
      service: frontend

  backend:
    extends:
      file: "../compose.yaml"
      service: backend
    build:
      context: "../backend"
      dockerfile: "dev.Dockerfile"
    volumes:
      - "../backend/src:/app:ro"

  notifier-service:
    extends:
      file: "../compose.yaml"
      service: notifier-service

  database:
    extends:
      file: "../compose.yaml"
      service: database

volumes:
  db-data: {}
  db-config: {}

# secrets:
#   backend_mongodb_connection_uri:
#     file: "../secrets/backend/mongodb_connection_uri"

networks:
  internet:
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"
  proxy:
    internal: true
  service:
    internal: true
