name: "task-manager-dev"

services:
  proxy01:
    extends:
      file: ../compose.yaml
      service: proxy01

  frontend:
    extends:
      file: ../compose.yaml
      service: frontend

  backend:
    build:
      context: "../backend"
      dockerfile: "dev.Dockerfile"
    volumes:
      - "../backend/src:/app:ro"
    networks:
      internet: {}
      proxy:
        aliases:
          - backend-proxy

networks:
  internet:
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"
  proxy:
    internal: true
  service:
    internal: true
